// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexScssModule {
  export interface IIndexScss {
    akarmi: string
    colorBlack: string
    colorDdbBlack: string
    colorDdbBlue: string
    colorDdbGray: string
    colorDdbGreen: string
    colorDdbRed: string
    colorDdbYellow: string
    colorGreen: string
    colorPurple: string
    colorYellow: string
    marginTopDesktop: string
    myIndex: string
  }
}

declare const IndexScssModule: IndexScssModule.IIndexScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexScssModule.IIndexScss
}

export = IndexScssModule
