// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MyIndexScssModule {
  export interface IMyIndexScss {
    "my-index": string
    myIndex: string
  }
}

declare const MyIndexScssModule: MyIndexScssModule.IMyIndexScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MyIndexScssModule.IMyIndexScss
}

export = MyIndexScssModule
